version: '3.5'

networks:
  application:

services:
  database:
    container_name: ckompiler-database
    restart: unless-stopped
    image: postgres
    env_file: .env
    volumes:
      - ./volume/postgres:/data/postgres
    expose:
      - "5432"
    networks:
      - application
