server:
  http2:
    enabled: true

spring:
  jpa:
    generate-ddl: off
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
      hibernate:
        default_schema: public
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ckompiler}
    username: ${POSTGRES_USERNAME:ckompiler}
    password: ${POSTGRES_PASSWORD:ckompiler}
  sql:
    init:
      mode: always
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ckompiler-internals-explorer.eu.auth0.com/
          audiences:
            - https://slak44.github.io/ckompiler/

---

spring:
  config:
    activate:
      on-profile: development
ckompiler:
  allowed-origin: http://localhost:4200
