{
 "title": "Internals Explorer Backend",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Request Latency/Duration",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum[$__rate_interval])) / sum(increase(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Avg Error %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "$ErrorRate * 100 / $RequestRate",
     "type": "math"
    }
   ]
  },
  {
   "title": "WebSocket Broker Processed Messages",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(executor_completed_tasks_total{name=\"clientInboundChannelExecutor\"}[$__rate_interval]))",
     "legendFormat": "Received messages"
    },
    {
     "expr": "sum(increase(executor_completed_tasks_total{name=\"clientOutboundChannelExecutor\"}[$__rate_interval]))",
     "legendFormat": "Sent messages"
    }
   ]
  },
  {
   "title": "WebSocket Broker Queued Messages",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(executor_queued_tasks{name=\"clientInboundChannelExecutor\"}[$__rate_interval]))",
     "legendFormat": "Received messages"
    },
    {
     "expr": "sum(increase(executor_queued_tasks{name=\"clientOutboundChannelExecutor\"}[$__rate_interval]))",
     "legendFormat": "Sent messages"
    }
   ]
  }
 ]
}