scrape_configs:
  - job_name: 'InternalsExplorerBackendMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['internals-explorer-backend:8080']
        labels:
          application: 'CKompiler Internals Explorer Backend'
