name: Build Kotlin/JS, Angular, Spring and deploy site
on:
  push:
    branches:
      - master
jobs:
  Build-ckompiler-JS-Distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Gradle and cache
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: jsBrowserDistribution
      - name: Archive JS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ckompiler-js-dist
          path: |
            build/js/packages/ckompiler/
            !build/js/packages/ckompiler/node_modules
            !build/js/packages/ckompiler/webpack.config.js
            !build/js/packages/ckompiler/kotlin/test
  Build-Internals-Explorer-Angular:
    runs-on: ubuntu-latest
    needs: Build-ckompiler-JS-Distribution
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: internals-explorer/node_modules
          key: ${{ runner.os }}-${{ hashFiles('internals-explorer/package-lock.json') }}
      - name: Download ckompiler JS artifacts
        uses: actions/download-artifact@v3
        with:
          name: ckompiler-js-dist
      - name: Move artifacts
        shell: bash
        run: mkdir -p build/js/packages/ckompiler/ && mv kotlin/ build/js/packages/ckompiler/
      - run: npm install
        working-directory: build/js/packages/ckompiler/
      - run: npm install
        working-directory: internals-explorer
      - name: Run eslint
        run: npx eslint 'src/**/*.ts'
        working-directory: internals-explorer
      - name: Angular Build
        run: npx ng build --base-href /ckompiler/
        working-directory: internals-explorer
      - name: Archive Angular artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ckompiler-angular-dist
          path: internals-explorer/dist/
  Build-Internals-Explorer-Spring:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build app and docker image with Gradle and cache
        uses: burrunan/gradle-cache-action@v1
        with:
          build-root-directory: internals-explorer-backend
          arguments: bootBuildImage --imageName ghcr.io/slak44/ckompiler-backend:latest --publishImage
          properties: |
            docker.publishRegistry.username=${{ github.actor }}
            docker.publishRegistry.password=${{ secrets.GITHUB_TOKEN }}
  Build-Sphinx-Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: 'documentation/'
      - name: Archive Sphinx documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ckompiler-sphinx-docs
          path: documentation/build/html
  Deploy-GH-Pages:
    runs-on: ubuntu-latest
    needs:
      - Build-Internals-Explorer-Angular
      - Build-Sphinx-Docs
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Angular artifacts
        uses: actions/download-artifact@v3
        with:
          name: ckompiler-angular-dist
      - run: mkdir documentation
        working-directory: internals-explorer
      - name: Get Sphinx artifacts
        uses: actions/download-artifact@v3
        with:
          name: ckompiler-sphinx-docs
          path: internals-explorer/documentation
      - name: Fix 404 page for SPA routes
        run: cp index.html 404.html
        working-directory: internals-explorer
      - name: Disable Jekyll Processing
        run: touch .nojekyll
        working-directory: internals-explorer
      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages
          folder: internals-explorer

concurrency:
  group: env-${{ github.head_ref }}
  cancel-in-progress: true
