name: Build Kotlin/JS, Angular and deploy site
on:
  push:
    branches:
      - master
jobs:
  Build-ckompiler-JS-Distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle and cache
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: jsBrowserDistribution
      - name: Archive JS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ckompiler-js-dist
          path: |
            build/js/packages/ckompiler/
            !build/js/packages/ckompiler/node_modules
            !build/js/packages/ckompiler/webpack.config.js
            !build/js/packages/ckompiler/kotlin/test
  Build-Deploy-Internals-Explorer-Angular:
    runs-on: ubuntu-latest
    needs: Build-ckompiler-JS-Distribution
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: internals-explorer/node_modules
          key: ${{ runner.os }}-${{ hashFiles('internals-explorer/package-lock.json') }}
      - name: Download ckompiler JS artifacts
        uses: actions/download-artifact@v2
        with:
          name: ckompiler-js-dist
      - name: Move artifacts
        shell: bash
        run: mkdir -p build/js/packages/ckompiler/ && mv kotlin/ build/js/packages/ckompiler/
      - run: npm install
        working-directory: build/js/packages/ckompiler/
      - run: npm install
        working-directory: internals-explorer
      - name: Angular Build
        run: npx ng build --base-href /ckompiler/
        working-directory: internals-explorer
      - name: Fix 404 page for SPA routes
        run: cp index.html 404.html
        working-directory: internals-explorer/dist/internals-explorer
      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: internals-explorer/dist/internals-explorer
#      - name: Archive Angular artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: ckompiler-angular-dist
#          path: |
#            internals-explorer/dist/
#  Deploy-GH-Pages:
#    runs-on: ubuntu-latest
#    needs: Build-Internals-Explorer-Angular
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - name: Get Angular artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: ckompiler-angular-dist
#      - name: Deploy to Github pages
#        uses: JamesIves/github-pages-deploy-action@4.1.7
#        with:
#          branch: gh-pages
#          folder: internals-explorer

concurrency:
  group: env-${{ github.head_ref }}
  cancel-in-progress: true
