name: Build Kotlin/JS
on:
  push:
    branches:
      - master
jobs:
  Build-ckompiler-JS-Distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with gradle
        run: |
          ./gradlew -g "./dot-gradle" jsBrowserDistribution
      - name: Archive JS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ckompiler-js-dist
          path: |
            build/js/packages/ckompiler/kotlin
            !build/js/packages/ckompiler/kotlin/test

concurrency:
  group: env-${{ github.head_ref }}
  cancel-in-progress: true
